name: Contbuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      #- name: install cargo sort
      #  run: cargo install cargo-sort
      - name: install nightly
        run: rustup toolchain install nightly
      - name: install rustfmt nightly
        run: rustup component add rustfmt --toolchain nightly
      #- name: cargo sort
      #  run: cargo sort --check
      - name: cargo fmt
        run: cargo +nightly fmt --check
      - name: cargo build
        run: cargo build --all-targets --all-features
      - name: clippy
        run: cargo clippy --all-features -- -D warnings
      - name: cargo test
        run: cargo test --all-targets --all-features
      - name: cargo doc tests
        run: cargo test --doc --all-features
